name: Build Docker NO CACHE self-hosted
on:
  workflow_dispatch

jobs:
  push_to_registry:
    name: Docker build imagined-harrier-user-project
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
