name: Build Docker NO CACHE self-hosted
on:
  workflow_dispatch

jobs:
  push_to_registry:
    name: Docker build imagined-harrier-user-project
    runs-on: self-hosted
    steps:
      - name: bing bong
      - run: echo "hi"
          
      
