name: "Run Fake Setup Harrier Action V4"
on:
  workflow_dispatch:  # Allows manual triggering

# permissions:
#   actions: write               # Allows managing workflow artifacts
#   workflow: write             # Allows triggering and managing workflows
#   admin:org: write             # Enables organization-level administrative actions
#   webhooks: write              # Allows creation, update, and deletion of webhooks

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Print some values from the github context object"
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository ID: ${{ github.repository_id }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Server URL: ${{ github.server_url }}"
          echo "API URL: ${{ github.api_url }}"
        
      - name: "Run My First Action"
        uses: 2408-capstone-team5/fake-setup-harrier-action@latest
        with:
          my-secret: "${{ secrets.MY_SECRET }}"
          your-secret: "${{ github.repository_id }}"
          runner-os: "${{ runner.os }}"
          org: "${{github.repository_owner}}"
          joel-pat: "${{secrets.JOEL_PAT}}"
          
      - name: "Fetch Registration Token for Harrier runner"
        run: |
          echo "hello world"
          echo ${{github.repository_owner}}
          echo ${{secrets.JOEL_PAT}}
          
          registration_token=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.JOEL_PAT}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{github.repository_owner}}/actions/runners/registration-token)

          token=$(echo "$registration_token" | jq -r '.token')
          echo "Runner registration token: $token"

