name: "Run Fake Setup Harrier Action V0"
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Print some values"
        run: |
          echo "Charlie Foxtrot"
          echo "Workflow ID: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Head Commit SHA: ${{ github.sha }}"
          
      - name: "Run My First Action"
        uses: 2408-capstone-team5/fake-setup-harrier-action@v1
        with:
          example_input: "${{ secrets.MY_SECRET }}"
