name: "Run My First GitHub Action"
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Run My First Action"
        uses: 2408-capstone-team5/my-first-github-action@v1
        with:
          example_input: "${{ secrets.MY_SECRET }}"
