name: "Run Fake Setup Harrier Action V4"
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Print some values from the github context object"
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository ID: ${{ github.repository_id }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Server URL: ${{ github.server_url }}"
          echo "API URL: ${{ github.api_url }}"
        
      - name: "Run My First Action"
        uses: 2408-capstone-team5/fake-setup-harrier-action@v4
        with:
          my-secret: "${{ secrets.MY_SECRET }}"
          your-secret: "${{ github.repository_id }}"
          runner-os: "${{ runner.os }}"
      - name: "Fetch Registration Token for Harrier runner"
        run: |
          echo "hello world"
          echo ${{github.repository_owner}}
          echo ${{secrets.GITHUB_TOKEN}}
          curl -X POST \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/${{github.repository_owner}}/actions/runners/registration-token
