name: "Run Fake Setup Harrier Action V4.5"
on:
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Run Harrier Setup Action"
        uses: 2408-capstone-team5/fake-setup-harrier-action@v4.5
        with:
          my-secret: "${{ secrets.MY_SECRET }}"
          your-secret: "${{ github.repository_id }}"
          runner-os: "${{ runner.os }}"
          org: "${{github.repository_owner}}"
          joel-pat: "${{secrets.JOEL_PAT}}"
          
